### ISSUE TITLE
Error Cannot use yii\base\Object as Object because 'Object' is a special class name PHP 7.2

### ISSUE THREAD

**Issue by Fendyanto** [ichsanmust/yii2-grid#1]

**Comment by ichsanmust** [comment]
please tell me what the spesific error...

**Comment by Fendyanto** [comment]
Pas dipake di localhost bisa, tapi pas diupload ke hosting muncul 

> This page isn’t working
> xxxx.xxxxxx is currently unable to handle this request.
> HTTP ERROR 500

**Comment by ichsanmust** [comment]
apa bisa dipastikan karena extension ini jadi error di server atau mungkin ada hal lain? kalo bisa pastikan dulu, mungkin hide dulu komponen extension ini. untuk cek lagi

**Comment by Fendyanto** [comment]
sudah mas, kalau dihilangkan column checkboxnya yg ini  halamannya bisa dibuka

```
[   
                'class' => 'ichsanmust\grid\CheckboxColumnSelectTools',  // class select nya memakai ini
                'name'=>'choose', // nama untuk checkbox
                'uniqueValue'=>'id_berkas', // value unique yang akan di select
                // 'rowHighlight' => true,
                // 'rowSelectedClass' => GridView::TYPE_INFO,
                // 'valueInit'=> array(3,2), // value data selected saat inisiasi gridview
                /*'valueInitSingle'=> function ($model, $key, $index, $column) { // value data selected per single data
                        if($model->STATUS == 3){ 
                            return true;
                        }else{
                            return false;
                        } 
                    },
                */
                // 'disabledCheckboxOnValue' =>true, // saat valueInit ada datanya, checkbox yang ter select akan di disabled
                'checkedCheckboxOnValue' => true, // saat valueInit ada datanya, checkbox yang ter select akan di checked    
        ]
```

**Comment by ichsanmust** [comment]
oh. trimakasih atas info nya, ada kemungkinan di component class nya ada yang salah syntax atau beda versi php, jadi error. kalo memungkin kan, settingan server nya, untuk error reporting nya boleh di nyalain, supaya error nya keliatan, bukan cuma 

This page isn’t working
xxxx.xxxxxx is currently unable to handle this request.
HTTP ERROR 500

biar lebih enak tracing error nya, soalnya selama ini belum pernah issue.
kalo ketauan error reporting nya akan memudahkan saya untuk memperbaiki nya.
terima kasih sebelum nya

**Comment by Fendyanto** [comment]
itu harus akses php.ini ya? saya gak dapet aksesnya mas

untuk versi servernya :

Apache Version | 2.4.41
-- | --
PHP Version | 7.2.24

**Comment by ichsanmust** [comment]
iya harus akses config php nya.
agak sulit kalo gak liat full pesan error nya.
apa id_berkas ini bener penulisan nya? takutnya case sensitive ( besar kecilnya huruf) 
kalo d local pake windows kah?

**Comment by Fendyanto** [comment]
iya sudah bener id_berkas.

 di local windows servernya Apache/2.4.39 (Win64) PHP/7.1.28

saya coba hubungi yang punya akses dulu ya, kalau sudah bisa nanti saya update lagi

Terima kasih sebelumnya 👍

**Comment by ichsanmust** [comment]
ok...

**Comment by ichsanmust** [comment]
oh iya saya lupa, apa bener sudah terinstall extension nya, di vendor, takutnya belum terinstall, belum di 
composer install di server. semacam itu. 

class ini 'class' => 'ichsanmust\grid\CheckboxColumnSelectTools'
kemungkinan tidak ditemukan

**Comment by Fendyanto** [comment]
iya sudah saya install dengan file archive, saya taruh di vendor dan sudah diatur aliasnya, cara yang sama berhasil di local. 

sudah saya pastikan juga karena kalau tidak benar installnya akan keluar error tidak ditemukan. 

saya coba juga panggil class bawaan yang disertakan ex: SerialColumn tapi tidak muncul juga

**Comment by ichsanmust** [comment]
ok. berarti nunggu pesan error nya aja biar pasti. dari tadi saya nebak nebak aja.

**Comment by Fendyanto** [comment]
okee..

karena semua class gak bisa, mungkin di extend class Column nya?
saya nebak nebak juga

maaf merepotkan

**Comment by ichsanmust** [comment]
kalo class Column.php nya itu bawaan yii2 nya sih , saya cuman bikin class CheckboxColumnSelectTools.php
cuman Column.php saya copy dan bawa ke folder exension saya.

gpp. gak merepotkan ko cuman penasaran aja
mending drpada nebak nebak. error message nya usahain munculin dulu ya. biar pasti.

**Comment by Fendyanto** [comment]
Cannot use yii\base\Object as Object because 'Object' is a special class name

 in D:\xampp\htdocs\siveranew\_protected\vendor\ichsanmust\yii2-grid\src\Column.php

`use yii\base\Object;`

**Comment by Fendyanto** [comment]
> Cannot use yii\base\Object as Object because 'Object' is a special class name
> 
> in D:\xampp\htdocs\siveranew_protected\vendor\ichsanmust\yii2-grid\src\Column.php
> 
> `use yii\base\Object;`

itu ya kak errornya, terima kasih

**Comment by Fendyanto** [comment]
Solved ganti Object dengan BaseObject 

> olved. since 2.0.13, the class name Object is invalid since PHP 7.2, use [[BaseObject]] instead.

**Comment by ichsanmust** [comment]
ok mantap.

**Comment by ichsanmust** [comment]
makasih udah pake extension nya, semoga bermanfaat...
