### ISSUE TITLE
enable rowHighlight

### ISSUE THREAD

**Issue by Fendyanto** [ichsanmust/yii2-grid#2]
kira-kira memungkinkan gak ya kalau ditambahkan rowhighlight? 

Terima kasih

**Comment by ichsanmust** [comment]
boleh ada gambar / screenshoot contoh rowhighlight seperti apa? apa saat terselect nya atau bagaimana nya

**Comment by Fendyanto** [comment]
Iya jadi pada saat suatu row terselect checkboxnya maka warnanya ganti misal warna biru, jadi keliatan row mana aja yang sudah terpilih. Kalau di checkboxcolumnnya kartik ada parameter rowHighlight => True

**Comment by Fendyanto** [comment]
![image](https://user-images.githubusercontent.com/57136387/72115470-be00bc00-3379-11ea-8390-95a8b02b38de.png)
